language: android
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
env:
  global:
  - ANDROID_API=22
  - EMULATOR_API=22
  - ANDROID_BUILD_TOOLS=27.0.1
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ADB_INSTALL_TIMEOUT=5
android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - platform-tools
  - android-$ANDROID_API
  - extra-google-google_play_services
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API
  - sys-img-armeabi-v7a-google_apis-$ANDROID_API
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n2be0707768cdfbd4d05ab4bcbae066129ba66f5d" > "$ANDROID_HOME/licenses/Android\
  SDK\ License"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55 \nd56f5187479451eabf01fb78af6dfcb131a6481e"
  > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n79120722343a6f314e0719f863036c702b0e6b2a \n84831b9409646a918e30573bab4c9c91346d8abd"
  > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- echo -e "\nd975f751698a77b662f1254ddbeed3901e976f5a" > "$ANDROID_HOME/licenses/intel-android-extra-license"
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
